
INSERT INTO `g84hn_cantons` ( `shortcode`, `german`, `french`, `italian`, `language`, `created_at`, `updated_at`) VALUES
( 'BE', 'Bern', 'Berne', 'Berna', 'de',now(), now()),
( 'VD', 'Waadt', 'Vaud', 'Vaud', 'fr',now(), now()),
( 'LU', 'Luzern', 'Lucerne', 'Lucerna', 'de',now(), now()),
( 'GE', 'Genf', 'Genève', 'Ginevra', 'fr',now(), now()),
( 'AI', 'Appenzell Innerrhoden', 'Appenzell Rhodes-Intérieures', 'Appenzello Interno', 'de',now(), now()),
( 'AR', 'Appenzell Ausserrhoden', 'Appenzell Rhodes-Extérieures', 'Appenzello Esterno', 'de',now(), now()),
( 'NW', 'Nidwalden', 'Obwald', 'Nidvaldo', 'de',now(), now()),
( 'OW', 'Obwalden', 'Nidwald', 'Obvaldo', 'de',now(), now()),
( 'TG', 'Thurgau', 'Thurgovie', 'Turgovia', 'de',now(), now()),
( 'SG', 'St. Gallen', 'Saint-Gall', 'San Gallo', 'de',now(), now()),
( 'BS', 'Basel-Stadt', 'Bâle-Ville', 'Basilea Città', 'de',now(), now()),
( 'BL', 'Basel-Landschaft', 'Bâle-Campagne', 'Basilea Campagna', 'de',now(), now()),
( 'SO', 'Solothurn', 'Soleure', 'Soletta', 'de',now(), now()),
( 'AG', 'Aargau', 'Argovie', 'Argovia', 'de',now(), now()),
( 'ZH', 'Zürich', 'Zurich', 'Zurigo', 'de',now(), now()),
( 'TI', 'Tessin', 'Tessin', 'Ticino', 'it',now(), now()),
( 'NE', 'Neuenburg', 'Neuchâtel', 'Neuchâtel', 'fr',now(), now()),
( 'FR', 'Freiburg', 'Fribourg', 'Friburgo', 'fr',now(), now()),
( 'UR', 'Uri', 'Uri', 'Uri', 'de',now(), now()),
( 'GR', 'Graubünden', 'Grisons', 'Grigioni', 'de',now(), now()),
( 'VS', 'Wallis', 'Valais', 'Vallese', 'fr',now(), now()),
( 'SH', 'Schaffhausen', 'Schaffhouse', 'Sciaffusa', 'de',now(), now()),
( 'GL', 'Glarus', 'Glaris', 'Glarona', 'de',now(), now()),
( 'SZ', 'Schwyz', 'Schwytz', 'Svitto', 'de',now(), now()),
( 'JU', 'Jura', 'Jura', 'Giura', 'fr',now(), now()),
( 'ZG', 'Zug', 'Zoug', 'Zugo', 'de',now(), now()),
( 'LI', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'de',now(), now()),
( 'INTL', 'Ausland', 'Pays étrangers', 'Paesi stranieri', 'de',now(), now());
