INSERT INTO `g84hn_countries` (`dename`, `frname`, `itname`, `enname`, `alpha_2`, `alpha_3`, `created_at`, `updated_at`) VALUES
( 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'AF', 'AFG',now(), now()),
( 'Ägypten', 'Égypte', 'Egitto', 'Egypt', 'EG', 'EGY',now(), now()),
( 'Åland', 'Îles Åland', 'Isole Åland', 'Åland Islands', 'AX', 'ALA',now(), now()),
( 'Albanien', 'Albanie', 'Albania', 'Albania', 'AL', 'ALB',now(), now()),
( 'Algerien', 'Algérie', 'Algeria', 'Algeria', 'DZ', 'DZA',now(), now()),
( 'Amerikanisch-Samoa', 'Samoa américaines', 'Samoa Americane', 'American Samoa', 'AS', 'ASM',now(), now()),
( 'Amerikanische Jungferninseln', 'Îles Vierges des États-Unis', 'Isole Vergini americane', 'Virgin Islands (U.S.)', 'VI', 'VIR',now(), now()),
( 'Andorra', 'Andorre', 'Andorra', 'Andorra', 'AD', 'AND',now(), now()),
( 'Angola', 'Angola', 'Angola', 'Angola', 'AO', 'AGO',now(), now()),
( 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'AI', 'AIA',now(), now()),
( 'Antarktika (Sonderstatus durch Antarktis-Vertrag)', 'Antarctique', 'Antartide', 'Antarctica', 'AQ', 'ATA',now(), now()),
( 'Antigua und Barbuda', 'Antigua-et-Barbuda', 'Antigua e Barbuda', 'Antigua and Barbuda', 'AG', 'ATG',now(), now()),
( 'Äquatorialguinea', 'Guinée équatoriale', 'Guinea Equatoriale', 'Equatorial Guinea', 'GQ', 'GNQ',now(), now()),
( 'Argentinien', 'Argentine', 'Argentina', 'Argentina', 'AR', 'ARG',now(), now()),
( 'Armenien', 'Arménie', 'Armenia', 'Armenia', 'AM', 'ARM',now(), now()),
( 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'AW', 'ABW',now(), now()),
( 'Aserbaidschan', 'Azerbaïdjan', 'Azerbaigian', 'Azerbaijan', 'AZ', 'AZE',now(), now()),
( 'Äthiopien', 'Éthiopie', 'Etiopia', 'Ethiopia', 'ET', 'ETH',now(), now()),
( 'Australien', 'Australie', 'Australia', 'Australia', 'AU', 'AUS',now(), now()),
( 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'BS', 'BHS',now(), now()),
( 'Bahrain', 'Bahreïn', 'Bahrein', 'Bahrain', 'BH', 'BHR',now(), now()),
( 'Bangladesch', 'Bangladesh', 'Bangladesh', 'Bangladesh', 'BD', 'BGD',now(), now()),
( 'Barbados', 'Barbade', 'Barbados', 'Barbados', 'BB', 'BRB',now(), now()),
( 'Belarus (Weißrussland)', 'Biélorussie', 'Bielorussia', 'Belarus', 'BY', 'BLR',now(), now()),
( 'Belgien', 'Belgique', 'Belgio', 'Belgium', 'BE', 'BEL',now(), now()),
( 'Belize', 'Belize', 'Belize', 'Belize', 'BZ', 'BLZ',now(), now()),
( 'Benin', 'Bénin', 'Benin', 'Benin', 'BJ', 'BEN',now(), now()),
( 'Bermuda', 'Bermudes', 'Bermuda', 'Bermuda', 'BM', 'BMU',now(), now()),
( 'Bhutan', 'Bhoutan', 'Bhutan', 'Bhutan', 'BT', 'BTN',now(), now()),
( 'Bolivien', 'Bolivie', 'Bolivia', 'Bolivia (Plurinational State of)', 'BO', 'BOL',now(), now()),
( 'Bonaire, Sint Eustatius und Saba (Niederlande)', 'Pays-Bas caribéens', 'Isole BES', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES',now(), now()),
( 'Bosnien und Herzegowina', 'Bosnie-Herzégovine', 'Bosnia ed Erzegovina', 'Bosnia and Herzegovina', 'BA', 'BIH',now(), now()),
( 'Botswana', 'Botswana', 'Botswana', 'Botswana', 'BW', 'BWA',now(), now()),
( 'Bouvetinsel', 'Île Bouvet', 'Isola Bouvet', 'Bouvet Island', 'BV', 'BVT',now(), now()),
( 'Brasilien', 'Brésil', 'Brasile', 'Brazil', 'BR', 'BRA',now(), now()),
( 'Britische Jungferninseln', 'Îles Vierges britanniques', 'Isole Vergini britanniche', 'Virgin Islands (British)', 'VG', 'VGB',now(), now()),
( 'Britisches Territorium im Indischen Ozean', 'Territoire britannique de l\'océan Indien', 'Territorio britannico dell\'Oceano Indiano', 'British Indian Ocean Territory', 'IO', 'IOT',now(), now()),
( 'Brunei Darussalam', 'Brunei', 'Brunei', 'Brunei Darussalam', 'BN', 'BRN',now(), now()),
( 'Bulgarien', 'Bulgarie', 'Bulgaria', 'Bulgaria', 'BG', 'BGR',now(), now()),
( 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'BF', 'BFA',now(), now()),
( 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'BI', 'BDI',now(), now()),
( 'Chile', 'Chili', 'Cile', 'Chile', 'CL', 'CHL',now(), now()),
( 'China', 'Chine', 'Cina', 'China', 'CN', 'CHN',now(), now()),
( 'Cookinseln', 'Îles Cook', 'Isole Cook', 'Cook Islands', 'CK', 'COK',now(), now()),
( 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'CR', 'CRI',now(), now()),
( 'Côte d’Ivoire (Elfenbeinküste)', 'Côte d\'Ivoire', 'Costa d\'Avorio', 'Ivory Coast\n', 'CI', 'CIV',now(), now()),
( 'Curaçao', 'Curaçao', 'Curaçao', 'Curaçao', 'CW', 'CUW',now(), now()),
( 'Dänemark', 'Danemark', 'Danimarca', 'Denmark', 'DK', 'DNK',now(), now()),
( 'Deutschland', 'Allemagne', 'Germania', 'Germany', 'DE', 'DEU',now(), now()),
( 'Dominica', 'Dominique', 'Dominica', 'Dominica', 'DM', 'DMA',now(), now()),
( 'Dominikanische Republik', 'République dominicaine', 'Rep. Dominicana', 'Dominican Republic', 'DO', 'DOM',now(), now()),
( 'Dschibuti', 'Djibouti', 'Gibuti', 'Djibouti', 'DJ', 'DJI',now(), now()),
( 'Ecuador', 'Équateur (pays)', 'Ecuador', 'Ecuador', 'EC', 'ECU',now(), now()),
( 'El Salvador', 'Salvador', 'El Salvador', 'El Salvador', 'SV', 'SLV',now(), now()),
( 'Eritrea', 'Érythrée', 'Eritrea', 'Eritrea', 'ER', 'ERI',now(), now()),
( 'Estland', 'Estonie', 'Estonia', 'Estonia', 'EE', 'EST',now(), now()),
( 'Falklandinseln', 'Malouines', 'Isole Falkland', 'Falkland Islands (Malvinas)', 'FK', 'FLK',now(), now()),
( 'Färöer', 'Îles Féroé', 'Fær Øer', 'Faroe Islands', 'FO', 'FRO',now(), now()),
( 'Fidschi', 'Fidji', 'Figi', 'Fiji', 'FJ', 'FJI',now(), now()),
( 'Finnland', 'Finlande', 'Finlandia', 'Finland', 'FI', 'FIN',now(), now()),
( 'Frankreich', 'France', 'Francia', 'France', 'FR', 'FRA',now(), now()),
( 'Französisch-Guayana', 'Guyane', 'Guyana francese', 'French Guiana', 'GF', 'GUF',now(), now()),
( 'Französisch-Polynesien', 'Polynésie française', 'Polinesia Francese', 'French Polynesia', 'PF', 'PYF',now(), now()),
( 'Französische Süd- und Antarktisgebiete', 'Terres australes et antarctiques françaises', 'Terre australi e antartiche francesi', 'French Southern Territories', 'TF', 'ATF',now(), now()),
( 'Gabun', 'Gabon', 'Gabon', 'Gabon', 'GA', 'GAB',now(), now()),
( 'Gambia', 'Gambie', 'Gambia', 'Gambia', 'GM', 'GMB',now(), now()),
( 'Georgien', 'Géorgie (pays)', 'Georgia', 'Georgia', 'GE', 'GEO',now(), now()),
( 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'GH', 'GHA',now(), now()),
( 'Gibraltar', 'Gibraltar', 'Gibilterra', 'Gibraltar', 'GI', 'GIB',now(), now()),
( 'Grenada', 'Grenade (pays)', 'Grenada', 'Grenada', 'GD', 'GRD',now(), now()),
( 'Griechenland', 'Grèce', 'Grecia', 'Greece', 'GR', 'GRC',now(), now()),
( 'Grönland', 'Groenland', 'Groenlandia', 'Greenland', 'GL', 'GRL',now(), now()),
( 'Guadeloupe', 'Guadeloupe', 'Guadalupa', 'Guadeloupe', 'GP', 'GLP',now(), now()),
( 'Guam', 'Guam', 'Guam', 'Guam', 'GU', 'GUM',now(), now()),
( 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'GT', 'GTM',now(), now()),
( 'Guernsey (Kanalinsel)', 'Guernesey', 'Guernsey', 'Guernsey', 'GG', 'GGY',now(), now()),
( 'Guinea', 'Guinée', 'Guinea', 'Guinea', 'GN', 'GIN',now(), now()),
( 'Guinea-Bissau', 'Guinée-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'GW', 'GNB',now(), now()),
( 'Guyana', 'Guyana', 'Guyana', 'Guyana', 'GY', 'GUY',now(), now()),
( 'Haiti', 'Haïti', 'Haiti', 'Haiti', 'HT', 'HTI',now(), now()),
( 'Heard und McDonaldinseln', 'Îles Heard-et-MacDonald', 'Isole Heard e McDonald', 'Heard Island and McDonald Islands', 'HM', 'HMD',now(), now()),
( 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'HN', 'HND',now(), now()),
( 'Hongkong', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'HK', 'HKG',now(), now()),
( 'Indien', 'Inde', 'India', 'India', 'IN', 'IND',now(), now()),
( 'Indonesien', 'Indonésie', 'Indonesia', 'Indonesia', 'ID', 'IDN',now(), now()),
( 'Insel Man', 'Île de Man', 'Isola di Man', 'Isle of Man', 'IM', 'IMN',now(), now()),
( 'Irak', 'Irak', 'Iraq', 'Iraq', 'IQ', 'IRQ',now(), now()),
( 'Iran', 'Iran', 'Iran', 'Iran', 'IR', 'IRN',now(), now()),
( 'Irland', 'Irlande', 'Irlanda', 'Ireland', 'IE', 'IRL',now(), now()),
( 'Island', 'Islande', 'Islanda', 'Iceland', 'IS', 'ISL',now(), now()),
( 'Israel', 'Israël', 'Israele', 'Israel', 'IL', 'ISR',now(), now()),
( 'Italien', 'Italie', 'Italia', 'Italy', 'IT', 'ITA',now(), now()),
( 'Jamaika', 'Jamaïque', 'Giamaica', 'Jamaica', 'JM', 'JAM',now(), now()),
( 'Japan', 'Japon', 'Giappone', 'Japan', 'JP', 'JPN',now(), now()),
( 'Jemen', 'Yémen', 'Yemen', 'Yemen', 'YE', 'YEM',now(), now()),
( 'Jersey (Kanalinsel)', 'Jersey', 'Jersey', 'Jersey', 'JE', 'JEY',now(), now()),
( 'Jordanien', 'Jordanie', 'Giordania', 'Jordan', 'JO', 'JOR',now(), now()),
( 'Kaimaninseln', 'Îles Caïmans', 'Isole Cayman', 'Cayman Islands', 'KY', 'CYM',now(), now()),
( 'Kambodscha', 'Cambodge', 'Cambogia', 'Cambodia', 'KH', 'KHM',now(), now()),
( 'Kamerun', 'Cameroun', 'Camerun', 'Cameroon', 'CM', 'CMR',now(), now()),
( 'Kanada', 'Canada', 'Canada', 'Canada', 'CA', 'CAN',now(), now()),
( 'Kap Verde', 'Cap-Vert', 'Capo Verde', 'Cabo Verde', 'CV', 'CPV',now(), now()),
( 'Kasachstan', 'Kazakhstan', 'Kazakistan', 'Kazakhstan', 'KZ', 'KAZ',now(), now()),
( 'Katar', 'Qatar', 'Qatar', 'Qatar', 'QA', 'QAT',now(), now()),
( 'Kenia', 'Kenya', 'Kenya', 'Kenya', 'KE', 'KEN',now(), now()),
( 'Kirgisistan', 'Kirghizistan', 'Kirghizistan', 'Kyrgyzstan', 'KG', 'KGZ',now(), now()),
( 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'KI', 'KIR',now(), now()),
( 'Kokosinseln', 'Îles Cocos', 'Isole Cocos (Keeling)', 'Cocos (Keeling) Islands', 'CC', 'CCK',now(), now()),
( 'Kolumbien', 'Colombie', 'Colombia', 'Colombia', 'CO', 'COL',now(), now()),
( 'Komoren', 'Comores (pays)', 'Comore', 'Comoros', 'KM', 'COM',now(), now()),
( 'Kongo', 'République démocratique du Congo', 'Rep. del Congo', 'Congo', 'CG', 'COG',now(), now()),
( 'Korea, Demokratische Volksrepublik (Nordkorea)', 'Corée du Nord', 'Corea del Nord', 'Korea (Democratic People\'s Republic of)', 'KP', 'PRK',now(), now()),
( 'Korea, Republik (Südkorea)', 'Corée du Sud', 'Corea del Sud', 'Korea (Republic of)', 'KR', 'KOR',now(), now()),
( 'Kroatien', 'Croatie', 'Croazia', 'Croatia', 'HR', 'HRV',now(), now()),
( 'Kuba', 'Cuba', 'Cuba', 'Cuba', 'CU', 'CUB',now(), now()),
( 'Kuwait', 'Koweït', 'Kuwait', 'Kuwait', 'KW', 'KWT',now(), now()),
( 'Laos, Demokratische Volksrepublik', 'Laos', 'Laos', 'Lao People\'s Democratic Republic', 'LA', 'LAO',now(), now()),
( 'Lesotho', 'Lesotho', 'Lesotho', 'Lesotho', 'LS', 'LSO',now(), now()),
( 'Lettland', 'Lettonie', 'Lettonia', 'Latvia', 'LV', 'LVA',now(), now()),
( 'Libanon', 'Liban', 'Libano', 'Lebanon', 'LB', 'LBN',now(), now()),
( 'Liberia', 'Liberia', 'Liberia', 'Liberia', 'LR', 'LBR',now(), now()),
( 'Libyen', 'Libye', 'Libia', 'Libya', 'LY', 'LBY',now(), now()),
( 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'LI', 'LIE',now(), now()),
( 'Litauen', 'Lituanie', 'Lituania', 'Lithuania', 'LT', 'LTU',now(), now()),
( 'Luxemburg', 'Luxembourg (pays)', 'Lussemburgo', 'Luxembourg', 'LU', 'LUX',now(), now()),
( 'Macau', 'Macao', 'Macao', 'Macao', 'MO', 'MAC',now(), now()),
( 'Madagaskar', 'Madagascar', 'Madagascar', 'Madagascar', 'MG', 'MDG',now(), now()),
( 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'MW', 'MWI',now(), now()),
( 'Malaysia', 'Malaisie', 'Malesia', 'Malaysia', 'MY', 'MYS',now(), now()),
( 'Malediven', 'Maldives', 'Maldive', 'Maldives', 'MV', 'MDV',now(), now()),
( 'Mali', 'Mali', 'Mali', 'Mali', 'ML', 'MLI',now(), now()),
( 'Malta', 'Malte', 'Malta', 'Malta', 'MT', 'MLT',now(), now()),
( 'Marokko', 'Maroc', 'Marocco', 'Morocco', 'MA', 'MAR',now(), now()),
( 'Marshallinseln', 'Îles Marshall (pays)', 'Isole Marshall', 'Marshall Islands', 'MH', 'MHL',now(), now()),
( 'Martinique', 'Martinique', 'Martinica', 'Martinique', 'MQ', 'MTQ',now(), now()),
( 'Mauretanien', 'Mauritanie', 'Mauritania', 'Mauritania', 'MR', 'MRT',now(), now()),
( 'Mauritius', 'Maurice,Île', 'Mauritius', 'Mauritius', 'MU', 'MUS',now(), now()),
( 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'YT', 'MYT',now(), now()),
( 'Mazedonien', 'République de Macédoine (pays)', 'Macedonia', 'Macedonia', 'MK', 'MKD',now(), now()),
( 'Mexiko', 'Mexique', 'Messico', 'Mexico', 'MX', 'MEX',now(), now()),
( 'Mikronesien', 'Micronésie (pays)', 'Micronesia', 'Micronesia (Federated States of)', 'FM', 'FSM',now(), now()),
( 'Moldawien (Republik Moldau)', 'Moldavie', 'Moldavia', 'Moldova (Republic of)', 'MD', 'MDA',now(), now()),
( 'Monaco', 'Monaco', 'Monaco', 'Monaco', 'MC', 'MCO',now(), now()),
( 'Mongolei', 'Mongolie', 'Mongolia', 'Mongolia', 'MN', 'MNG',now(), now()),
( 'Montenegro', 'Monténégro', 'Montenegro', 'Montenegro', 'ME', 'MNE',now(), now()),
( 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'MS', 'MSR',now(), now()),
( 'Mosambik', 'Mozambique', 'Mozambico', 'Mozambique', 'MZ', 'MOZ',now(), now()),
( 'Myanmar (Burma)', 'Birmanie', 'Birmania', 'Myanmar', 'MM', 'MMR',now(), now()),
( 'Namibia', 'Namibie', 'Namibia', 'Namibia', 'NA', 'NAM',now(), now()),
( 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'NR', 'NRU',now(), now()),
( 'Nepal', 'Népal', 'Nepal', 'Nepal', 'NP', 'NPL',now(), now()),
( 'Neukaledonien', 'Nouvelle-Calédonie', 'Nuova Caledonia', 'New Caledonia', 'NC', 'NCL',now(), now()),
( 'Neuseeland', 'Nouvelle-Zélande', 'Nuova Zelanda', 'New Zealand', 'NZ', 'NZL',now(), now()),
( 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'NI', 'NIC',now(), now()),
( 'Niederlande', 'Pays-Bas', 'Paesi Bassi', 'Netherlands', 'NL', 'NLD',now(), now()),
( 'Niger', 'Niger', 'Niger', 'Niger', 'NE', 'NER',now(), now()),
( 'Nigeria', 'Nigeria', 'Nigeria', 'Nigeria', 'NG', 'NGA',now(), now()),
( 'Niue', 'Niue', 'Niue', 'Niue', 'NU', 'NIU',now(), now()),
( 'Nördliche Marianen', 'Îles Mariannes du Nord', 'Isole Marianne Settentrionali', 'Northern Mariana Islands', 'MP', 'MNP',now(), now()),
( 'Norfolkinsel', 'Île Norfolk', 'Isola Norfolk', 'Norfolk Island', 'NF', 'NFK',now(), now()),
( 'Norwegen', 'Norvège', 'Norvegia', 'Norway', 'NO', 'NOR',now(), now()),
( 'Oman', 'Oman', 'Oman', 'Oman', 'OM', 'OMN',now(), now()),
( 'Österreich', 'Autriche', 'Austria', 'Austria', 'AT', 'AUT',now(), now()),
( 'Osttimor (Timor-Leste)', 'Timor oriental', 'Timor Est', 'Timor-Leste', 'TL', 'TLS',now(), now()),
( 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistan', 'PK', 'PAK',now(), now()),
( 'Staat Palästina', 'Palestine', 'Palestina', 'Palestine, State of', 'PS', 'PSE',now(), now()),
( 'Palau', 'Palaos', 'Palau', 'Palau', 'PW', 'PLW',now(), now()),
( 'Panama', 'Panama', 'Panama', 'Panama', 'PA', 'PAN',now(), now()),
( 'Papua-Neuguinea', 'Papouasie-Nouvelle-Guinée', 'Papua Nuova Guinea', 'Papua New Guinea', 'PG', 'PNG',now(), now()),
( 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay', 'PY', 'PRY',now(), now()),
( 'Peru', 'Pérou', 'Perù', 'Peru', 'PE', 'PER',now(), now()),
( 'Philippinen', 'Philippines', 'Filippine', 'Philippines', 'PH', 'PHL',now(), now()),
( 'Pitcairninseln', 'Îles Pitcairn', 'Isole Pitcairn', 'Pitcairn', 'PN', 'PCN',now(), now()),
( 'Polen', 'Pologne', 'Polonia', 'Poland', 'PL', 'POL',now(), now()),
( 'Portugal', 'Portugal', 'Portogallo', 'Portugal', 'PT', 'PRT',now(), now()),
( 'Puerto Rico', 'Porto Rico', 'Porto Rico', 'Puerto Rico', 'PR', 'PRI',now(), now()),
( 'Réunion', 'La Réunion', 'Riunione', 'Réunion', 'RE', 'REU',now(), now()),
( 'Ruanda', 'Rwanda', 'Ruanda', 'Rwanda', 'RW', 'RWA',now(), now()),
( 'Rumänien', 'Roumanie', 'Romania', 'Romania', 'RO', 'ROU',now(), now()),
( 'Russische Föderation', 'Russie', 'Russia', 'Russian Federation', 'RU', 'RUS',now(), now()),
( 'Salomonen', 'Salomon', 'Isole Salomone', 'Solomon Islands', 'SB', 'SLB',now(), now()),
( 'Saint-Barthélemy', 'Saint-Barthélemy', 'Saint-Barthélemy', 'Saint Barthélemy', 'BL', 'BLM',now(), now()),
( 'Saint-Martin (franz. Teil)', 'Saint-Martin', 'Saint-Martin', 'Saint Martin (French part)', 'MF', 'MAF',now(), now()),
( 'Sambia', 'Zambie', 'Zambia', 'Zambia', 'ZM', 'ZMB',now(), now()),
( 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'WS', 'WSM',now(), now()),
( 'San Marino', 'Saint-Marin', 'San Marino', 'San Marino', 'SM', 'SMR',now(), now()),
( 'São Tomé und Príncipe', 'Sao Tomé-et-Principe', 'São Tomé e Príncipe', 'Sao Tome and Principe', 'ST', 'STP',now(), now()),
( 'Saudi-Arabien', 'Arabie saoudite', 'Arabia Saudita', 'Saudi Arabia', 'SA', 'SAU',now(), now()),
( 'Schweden', 'Suède', 'Svezia', 'Sweden', 'SE', 'SWE',now(), now()),
( 'Schweiz', 'Suisse', 'Svizzera', 'Switzerland', 'CH', 'CHE',now(), now()),
( 'Senegal', 'Sénégal', 'Senegal', 'Senegal', 'SN', 'SEN',now(), now()),
( 'Serbien', 'Serbie', 'Serbia', 'Serbia', 'RS', 'SRB',now(), now()),
( 'Seychellen', 'Seychelles', 'Seychelles', 'Seychelles', 'SC', 'SYC',now(), now()),
( 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'SL', 'SLE',now(), now()),
( 'Simbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'ZW', 'ZWE',now(), now()),
( 'Singapur', 'Singapour', 'Singapore', 'Singapore', 'SG', 'SGP',now(), now()),
( 'Sint Maarten (niederl. Teil)', 'Saint-Martin', 'Sint Maarten', 'Sint Maarten (Dutch part)', 'SX', 'SXM',now(), now()),
( 'Slowakei', 'Slovaquie', 'Slovacchia', 'Slovakia', 'SK', 'SVK',now(), now()),
( 'Slowenien', 'Slovénie', 'Slovenia', 'Slovenia', 'SI', 'SVN',now(), now()),
( 'Somalia', 'Somalie', 'Somalia', 'Somalia', 'SO', 'SOM',now(), now()),
( 'Spanien', 'Espagne', 'Spagna', 'Spain', 'ES', 'ESP',now(), now()),
( 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'LK', 'LKA',now(), now()),
( 'St. Helena', 'Sainte-Hélène, Ascension et Tristan da Cunha', 'Sant\'Elena, Ascensione e Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN',now(), now()),
( 'St. Kitts und Nevis', 'Saint-Christophe-et-Niévès', 'Saint Kitts e Nevis', 'Saint Kitts and Nevis', 'KN', 'KNA',now(), now()),
( 'St. Lucia', 'Sainte-Lucie', 'Santa Lucia', 'Saint Lucia', 'LC', 'LCA',now(), now()),
( 'Saint-Pierre und Miquelon', 'Saint-Pierre-et-Miquelon', 'Saint-Pierre e Miquelon', 'Saint Pierre and Miquelon', 'PM', 'SPM',now(), now()),
( 'St. Vincent und die Grenadinen', 'Saint-Vincent-et-les Grenadines', 'Saint Vincent e Grenadine', 'Saint Vincent and the Grenadines', 'VC', 'VCT',now(), now()),
( 'Südafrika', 'Afrique du Sud', 'Sudafrica', 'South Africa', 'ZA', 'ZAF',now(), now()),
( 'Sudan', 'Soudan', 'Sudan', 'Sudan', 'SD', 'SDN',now(), now()),
( 'Südgeorgien und die Südlichen Sandwichinseln', 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'Georgia del Sud e isole Sandwich meridionali', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS',now(), now()),
( 'Südsudan', 'Soudan du Sud', 'Sudan del Sud', 'South Sudan', 'SS', 'SSD',now(), now()),
( 'Suriname', 'Suriname', 'Suriname', 'Suriname', 'SR', 'SUR',now(), now()),
( 'Svalbard und Jan Mayen', 'Svalbard et ile Jan Mayen', 'Svalbard e Jan Mayen', 'Svalbard and Jan Mayen', 'SJ', 'SJM',now(), now()),
( 'Swasiland', 'Swaziland', 'Swaziland', 'Swaziland', 'SZ', 'SWZ',now(), now()),
( 'Syrien', 'Syrie', 'Siria', 'Syrian Arab Republic', 'SY', 'SYR',now(), now()),
( 'Tadschikistan', 'Tadjikistan', 'Tagikistan', 'Tajikistan', 'TJ', 'TJK',now(), now()),
( 'Republik China (Taiwan)', 'Taïwan / (République de Chine (Taïwan))', 'Taiwan', 'Taiwan, Province of China', 'TW', 'TWN',now(), now()),
( 'Tansania, Vereinigte Republik', 'Tanzanie', 'Tanzania', 'Tanzania, United Republic of', 'TZ', 'TZA',now(), now()),
( 'Thailand', 'Thaïlande', 'Thailandia', 'Thailand', 'TH', 'THA',now(), now()),
( 'Togo', 'Togo', 'Togo', 'Togo', 'TG', 'TGO',now(), now()),
( 'Tokelau', 'Tokelau', 'Tokelau', 'Tokelau', 'TK', 'TKL',now(), now()),
( 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'TO', 'TON',now(), now()),
( 'Trinidad und Tobago', 'Trinité-et-Tobago', 'Trinidad e Tobago', 'Trinidad and Tobago', 'TT', 'TTO',now(), now()),
( 'Tschad', 'Tchad', 'Ciad', 'Chad', 'TD', 'TCD',now(), now()),
( 'Tschechien', 'Tchéquie', 'Rep. Ceca', 'Czechia', 'CZ', 'CZE',now(), now()),
( 'Tunesien', 'Tunisie', 'Tunisia', 'Tunisia', 'TN', 'TUN',now(), now()),
( 'Türkei', 'Turquie', 'Turchia', 'Turkey', 'TR', 'TUR',now(), now()),
( 'Turkmenistan', 'Turkménistan', 'Turkmenistan', 'Turkmenistan', 'TM', 'TKM',now(), now()),
( 'Turks- und Caicosinseln', 'Îles Turks-et-Caïcos', 'Turks e Caicos', 'Turks and Caicos Islands', 'TC', 'TCA',now(), now()),
( 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'TV', 'TUV',now(), now()),
( 'Uganda', 'Ouganda', 'Uganda', 'Uganda', 'UG', 'UGA',now(), now()),
( 'Ukraine', 'Ukraine', 'Ucraina', 'Ukraine', 'UA', 'UKR',now(), now()),
( 'Ungarn', 'Hongrie', 'Ungheria', 'Hungary', 'HU', 'HUN',now(), now()),
( 'United States Minor Outlying Islands', 'Îles mineures éloignées des États-Unis', 'Isole minori esterne degli Stati Uniti', 'United States Minor Outlying Islands', 'UM', 'UMI',now(), now()),
( 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'UY', 'URY',now(), now()),
( 'Usbekistan', 'Ouzbékistan', 'Uzbekistan', 'Uzbekistan', 'UZ', 'UZB',now(), now()),
( 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'VU', 'VUT',now(), now()),
( 'Vatikanstadt', 'Saint-Siège (État de la Cité du Vatican)', 'Città del Vaticano', 'Holy See', 'VA', 'VAT',now(), now()),
( 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN',now(), now()),
( 'Vereinigte Arabische Emirate', 'Émirats arabes unis', 'Emirati Arabi Uniti', 'United Arab Emirates', 'AE', 'ARE',now(), now()),
( 'Vereinigte Staaten von Amerika', 'États-Unis', 'Stati Uniti', 'United States of America', 'US', 'USA',now(), now()),
( 'Vereinigtes Königreich Großbritannien und Nordirland', 'Royaume-Uni', 'Regno Unito', 'United Kingdom of Great Britain and Northern Irela', 'GB', 'GBR',now(), now()),
( 'Vietnam', 'Viêt Nam', 'Vietnam', 'Viet Nam', 'VN', 'VNM',now(), now()),
( 'Wallis und Futuna', 'Wallis-et-Futuna', 'Wallis e Futuna', 'Wallis and Futuna', 'WF', 'WLF',now(), now()),
( 'Weihnachtsinsel', 'Île Christmas', 'Isola di Natale', 'Christmas Island', 'CX', 'CXR',now(), now()),
( 'Westsahara', 'République arabe sahraouie démocratique', 'Sahara Occidentale', 'Western Sahara', 'EH', 'ESH',now(), now()),
( 'Zentralafrikanische Republik', 'République centrafricaine', 'Rep. Centrafricana', 'Central African Republic', 'CF', 'CAF',now(), now()),
( 'Zypern', 'Chypre (pays)', 'Cipro', 'Cyprus', 'CY', 'CYP',now(), now()),
( 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'XK', 'XKX',now(), now()),
( 'Niederländische Antillen', 'Antilles néerlandaises', 'Antille Olandesi', 'Netherlands Antilles', 'AN', 'ANT',now(), now());